language: r
dist: xenial
sudo: required
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - valgrind

branches:
  only:
    - "master"

r:
  - release
  - oldrel
  - devel

os:
  - linux

r_packages:
  - covr

after_success: 
  - test $TRAVIS_R_VERSION_STRING = 'release' && 
    test $TRAVIS_OS_NAME = 'linux' && 
    Rscript -e 'covr::codecov(quiet=FALSE)'
  - R -e "install.packages('${PKG_TARBALL}', repo=NULL, type='source')"
  - cd tests
  - R -d "valgrind --tool=memcheck --leak-check=full --track-origins=yes" --vanilla < test_kit.R
  - cd ..
