language: r
dist: xenial
sudo: required
cache: packages
warnings_are_errors: true

branches:
  only:
    - "master"

r:
  - oldrel
  - release
  - devel
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 3.1

os:
  - linux
