language: r
dist: xenial
sudo: required
cache: packages
warnings_are_errors: true

branches:
  only:
    - "master"

r:
  - release
  - oldrel
  - devel
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2

os:
  - linux

r_packages:
  - covr

after_success: 
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
