init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"

install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap

environment:
  _R_CHECK_FORCE_SUGGESTS_: false
  
  matrix:
  - R_VERSION: devel
    R_ARCH: x64

  - R_VERSION: devel
    R_ARCH: i386

  - R_VERSION: release
    R_ARCH: x64
    
matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  
